using System.ComponentModel.DataAnnotations;

namespace EduBoost.API.Features.Quizzes.Models;

/// <summary>Request body for submitting a single answer in adaptive tutoring mode</summary>
public class TutorAnswerRequest
{
    [Required] public string TopicId { get; set; } = "";
    [Required] public string QuestionId { get; set; } = "";
    [Required] public string QuestionText { get; set; } = "";
    [Required] public string SelectedAnswer { get; set; } = "";
    [Required] public string CorrectAnswer { get; set; } = "";
    public double Difficulty { get; set; } = 0.5;
    public double? ResponseTimeSeconds { get; set; }
}

/// <summary>Request body for getting a detailed explanation for a wrong answer</summary>
public class ExplainErrorRequest
{
    [Required] public string Question { get; set; } = "";
    [Required] public string CorrectAnswer { get; set; } = "";
    [Required] public string StudentAnswer { get; set; } = "";
}

/// <summary>An adaptive quiz question generated by the AI agent</summary>
public class TutorQuestionDto
{
    public string QuestionId { get; set; } = "";
    public string Question { get; set; } = "";
    public Dictionary<string, string> Options { get; set; } = new();
    public string CorrectAnswer { get; set; } = "";
    public string Explanation { get; set; } = "";
    public double DifficultyLevel { get; set; }
}

/// <summary>Record tutor practice session stats (streak, learning_sessions).</summary>
public class TutorCompletePracticeRequest
{
    [Required] public string TopicId { get; set; } = "";
    public int QuestionsAttempted { get; set; }
    public int CorrectAnswers { get; set; }
}

/// <summary>Result after submitting a single adaptive answer</summary>
public class TutorAnswerResult
{
    public bool IsCorrect { get; set; }
    public string Explanation { get; set; } = "";
    public string? Mastery { get; set; }
    public double? NewProbability { get; set; }
    public double? NewTheta { get; set; }
    public string? NextAction { get; set; }
}
